# Generated by Django 4.2.1 on 2023-06-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=10)),
                ('image', models.CharField(max_length=50)),
                ('release_date', models.DateField(max_length=50)),
                ('lte_exists', models.BooleanField(max_length=5)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
